# Generated by Django 3.2.12 on 2022-02-12 23:02

from django.db import migrations, models
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PixelTracking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.UUIDField(default=uuid.uuid4)),
                ('tracked_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, max_length=30)),
                ('url', models.URLField(db_index=True, max_length=30)),
            ],
        ),
    ]
